### ISSUE TITLE
Add config for this repo to run fine in a codespace (npm workspace issue)

### ISSUE THREAD

**Issue by liana-p** [nearform/owasp-top-ten-workshop#36]
Apparently codespaces don't use the right node or npm version by default (despite the .nvmrc file). This makes `npm install` not work properly because of workspace support.

We should look if there's a way to add a config file or some other way of telling codespaces to run the correct version of tools.

**Comment by simoneb** [comment]
https://docs.github.com/en/codespaces/setting-up-your-project-for-codespaces/setting-up-your-nodejs-project-for-codespaces#step-2-add-a-dev-container-configuration-to-your-repository-from-a-template

**Comment by coston** [comment]
An issue that could trip up user experience is if the user isn't using npm@7+. Following the readme instructions won't work at that point. To debug the issue, one has to know about npm workspaces, which some users may not have experienced yet.

Codespaces has some minor confusing behavior when using nvm. It does not respect the one' specified node version, which could lead to the wrong npm version.
 
<img width="600" alt="image" src="https://user-images.githubusercontent.com/7424180/191561404-f16f95a4-fd4c-45d8-946e-552a9fcd8b41.png">

**Comment by groozin** [comment]
I was able to run the project from codespaces no problem - seems that they updated their node version - it 20 by default now.

**Comment by coston** [comment]
Thanks for the update @groozin.
