### ISSUE TITLE
Ability to test vulnerabilities from the browser

### ISSUE THREAD

**Issue by simoneb** [nearform/owasp-top-ten-workshop#382]
Instead of using Postman, add a little web app to test vulnerabilities directly in the browser. E.g. inject image with URL.

I could be a small app that goes along with the slides, somehow.

Reach out to @marco-ippolito for any additional information.

**Comment by simoneb** [comment]
@bp289 can you follow up with Marco about this?

**Comment by bp289** [comment]
Hi, Sure thing. I'll be able to talk to Marco today if not, definitely at some point this week.

**Comment by bp289** [comment]
@simoneb just talked to Marco and cleared some things up, can continue with this ticket now 👍

**Comment by simoneb** [comment]
Closing as we're not going to do this
